Added method to update using named query
santanusinha/dropwizard-db-sharding-bundle pull request #42
Opened 2020-10-10 18:49 UTC by r0goyal

2020-10-20 05:15 UTC, santanusinha requested changes

2020-10-20 05:15 UTC, santanusinha commented on src/main/java/io/appform/dropwizard/sharding/dao/UpdateParams.java
> +public class UpdateParams {
Rename to `UpdateOperationMeta`

2020-10-21 05:52 UTC, r0goyal commented on src/main/java/io/appform/dropwizard/sharding/dao/UpdateParams.java
> +public class UpdateParams {
Done

2020-10-21 08:10 UTC, santanusinha approved these changes

2020-10-21 08:10 UTC, merged